name: network_repository
description: Dart package which manages network requests.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.3
  shared_preferences: ^2.0.6
  device_info_plus: ^2.1.0
